### ISSUE TITLE
Error with test environment credentials;

### ISSUE THREAD

**Issue by sha-phpnerd** [sanmai/gmopg#4]
I'm very new to GMO PG; I've been facing problem with integrating with my test environment credentials;     

- An unknown error occurred.
-     指定されたIDとパスワードのショップが存在しません。

Please help me
My Login to test environment web is success
 

> SHOP   Softzino Technologies (tshop00036769)
>  アドミニストレータ(ADMINISTRATOR)
but can't login with below config:

`\GMO\API\Defaults::setShopID('tshop00036769');
        \GMO\API\Defaults::setShopName('Softzino');
        \GMO\API\Defaults::setPassword('GMOshopPass');//not provided
        \GMO\API\Defaults::setMethods(new MethodsSandbox());`

    $payment = new \GMO\ImmediatePayment();
        // Unique ID for every payment; probably should be taken from an auto-increment field from the database.
        $payment->paymentId = 123;
        $payment->amount = 1000;
    // This card number can be used for tests.
        $payment->cardNumber = '4111111111111111';
    // A date in the future.
        $payment->cardYear = '2020';
        $payment->cardMonth = '7';
        $payment->cardCode = '123';

    // Returns false on an error.
        if (!$payment->execute()) {
            $errors = $payment->getErrors();
            echo '<ul>';
            foreach ($errors as $errorCode => $errorDescription) {
                // Show an error code and a description to the customer? Your choice.
                // Probably you want to log the error too.
                echo '<li>' . $errorDescription.'</li>';
            }
            echo '</ul>';
            return;
        }

    // Success!
        $response = $payment->getResponse();

**Comment by sanmai** [comment]
You got to set this constant to use test environment credentials:
```php
define('GMO_TRIAL_MODE', true);
```

**Comment by sanmai** [comment]
I've updated the README to make things more clear.

Feel free to reopen if that's not the solution.

**Comment by sha-phpnerd** [comment]
I've added this into my index.php in laravel project; and still getting same error; 
oh, this is to mention : I've been trying from my localhost on my PC; I'm trying this with my own credential got from GMO PG, I've asked to my client to provide me the test env. credentials; I'll try with his credentials and I'll let you know the result, Sir. Thank you so much for very fast response. 
`define('GMO_TRIAL_MODE', true);`

**Comment by sanmai** [comment]
OK, so apparently GMO PG won't let one use directly-entered card numbers, even for test accounts. For actual accounts it seems like you must pass the PCI DSS inspection. For test accounts there's [a procedure to enable direct card number usage](https://faq.gmo-pg.com/service/Detail.aspx?id=2043&page=0&listNo=0&category=0).

**Comment by sha-phpnerd** [comment]
Thank you very much Sir,
My problems are solved with credentials; I didn't know from where to get the shop API password; I was using shop login password for accessing API;
And was facing problem with credit card; got solution with your previous comment. Thanks again!
Would you please edit the readme file about getting shop password; this may help the new comers too like me.

**Comment by sanmai** [comment]
No problem! A more appropriate solution would be to upgrade the API implementation to use tokens, but I don't really have much time to dig any deeper into this, nor any of my current clients are using GMO PG these days. Any help is appreciated.
